import os
from fpdf import FPDF
from huggingface_hub import hf_hub_download


def get_font_path():
    return hf_hub_download(
        repo_id="mandar10/vitiligo-models",
        filename="DejaVuSans.ttf"
    )


class VitiligoPDF(FPDF):

    def header(self):
        self.set_font("DejaVu", "", 16)
        self.set_text_color(0, 102, 204)
        self.cell(0, 10, "Vitiligo Assessment Report", ln=True, align="C")
        self.ln(5)

    def add_section_title(self, title):
        self.set_text_color(0, 102, 204)
        self.set_font("DejaVu", "", 14)
        self.ln(5)
        self.cell(0, 8, title, ln=True)
        self.set_text_color(0, 0, 0)

    def add_paragraph(self, text):
        self.set_font("DejaVu", "", 12)
        self.multi_cell(0, 6, text)
        self.ln(2)

    def add_image_safe(self, image_path, width=120):
        if image_path and os.path.exists(image_path):
            self.ln(5)
            self.image(image_path, w=width)
            self.ln(5)


def generate_vitiligo_report(data: dict):

    pdf = VitiligoPDF()

    font_path = get_font_path()

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)

    pdf.add_font("DejaVu", "", font_path, uni=True)
    pdf.add_page()

    pdf.set_font("DejaVu", "", 12)

    # ---------------- Patient Info ----------------
    pdf.add_section_title("Patient Information")
    pdf.add_paragraph(f"Name: {data.get('patient_name')}")
    pdf.add_paragraph(f"Age: {data.get('age')}")
    pdf.add_paragraph(f"Gender: {data.get('gender')}")
    pdf.add_paragraph(f"Date: {data.get('date')}")

    # ---------------- Scores ----------------
    pdf.add_section_title("Score Summary")

    for section, score in data.get("section_scores", {}).items():
        pdf.add_paragraph(f"{section.capitalize()} Score: {score}")

    pdf.add_paragraph(f"Combined Score: {data.get('combined_score')}")

    #--------type-----------

    vitiligo_type = data.get("vitiligo_type")
    if vitiligo_type:
        pdf.add_section_title("Vitiligo Type Assessment")
        pdf.add_paragraph(f"Identified Type: {vitiligo_type}")

    # ---------------- Prediction ----------------
    pdf.add_section_title("Overall Risk Assessment")
    pdf.add_paragraph(f"Predicted Risk Level: {data.get('prediction')}")

    # ---------------- Insights ----------------
    insights = data.get("insights", [])
    if insights:
        pdf.add_section_title("Insights")
        for insight in insights:
            pdf.add_paragraph(insight)

    # ---------------- Conclusion ----------------
    conclusion = data.get("conclusion")
    if conclusion:
        pdf.add_section_title("Conclusion")
        pdf.add_paragraph(conclusion)

    # ---------------- Pie Chart ----------------
    chart_path = data.get("chart_path")
    if chart_path:
        pdf.add_section_title("Risk Distribution")
        pdf.add_image_safe(chart_path, width=130)

    # ---------------- Image Section (Optional) ----------------
    image_paths = data.get("image_paths", {})

    if image_paths:
        pdf.add_section_title("Image Analysis")

    for label, path in image_paths.items():
        if path:
            pdf.add_paragraph(label)
            pdf.add_image_safe(path)

    # ---------------- Disclaimer ----------------
    pdf.add_section_title("Disclaimer")
    pdf.add_paragraph(
        "This report is generated by AI-based software and is for informational purposes only. "
        "It is not a substitute for professional medical advice."
    )

    report_path = f"{data.get('patient_name')}_vitiligo_report.pdf"
    pdf.output(report_path)

    return report_path